<template>
  <el-container>
    <el-main>
      <div class="main_content">
        <div class="main_contit">
          <h2>杨小红</h2>
        </div>
        <div class="main_conDiv" id="vsb_content_2"><p class="vsbcontent_img">
          <p style="line-height: 150%; text-indent: 14px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">姓名：杨小红</span> </span></p>
          <p style="line-height: 150%; text-indent: 14px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">性别：女</span> </span></p>
          <p style="line-height: 150%; text-indent: 14px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">出生年月：</span> 1975.12.3 </span></p>
          <p style="line-height: 150%; text-indent: 14px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">籍贯：</span> <span style="font-family: 宋体;">甘肃省兰州市</span> </span></p>
          <p style="line-height: 150%; text-indent: 14px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">专业技术职务：</span> <span style="font-family: 宋体;">副教授</span> </span></p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">【教育经历】主要学习工作经历</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">1996——2000年在兰州商学院读本科，获企业管理学士学位；</span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">2000——2003年在兰州大学经济管理学院攻读硕士研究生，获管理学硕士学位，研究方向为组织行为学；</span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">2003——今，在西安工程大学管理学院营销系任教；</span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">2015-—今</span><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">，</span></span><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">西安交通大学管理学院工商管理专业博士研究生，研究方向为营销。</span></span></p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">【承担课程】</span> <span style="font-family: 宋体;">消费者行为学、市场营销学、服务营销学、市场研究</span></span></p>
          <p style="text-align: left; line-height: 150%; text-indent: 0px; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">【研究方向】</span></span> <span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">消费者行为、服务营销、市场营销</span></span></p>
          <p style="line-height: 29px;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">【主持与参与项目】</span></span></p>
          <p style="line-height: 29px; text-indent: 21px;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">1.“互联网+”背景下以制造业服务化带动陕西制造业转型升级的策略研究.陕西省软科学研究计划项目.</span> </p>
          <p style="line-height: 29px; text-indent: 21px;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">2.</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">供给侧改革下陕西制造业转型升级的对策研究</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">陕西省社科基金项目</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">.</span></p>
          <p style="line-height: 29px; text-indent: 21px;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">3.组织控制、自我控制方式选择及其对销售员个人绩效的影响研究</span> <span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">教育部人文社科项目</span>.</span></p>
          <p style="line-height: 29px; text-indent: 21px;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">4.直销商领导力的研究.陕西省教育厅项目.</span></p>
          <p style="line-height: 29px; text-indent: 21px;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">5.全球化时代的领导力研究.上海恩卓企业管理咨询有限公司项目.</span></p>
          <p style="line-height: 29px; text-indent: 21px;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">6.素质教育视角下网瘾的预防与戒除对策研究.西安工程大学项目.</span></p>
          <p style="line-height: 29px; text-indent: 21px;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">7.直销企业中的领导力研究.西安工程大学项目.</span></p>
          <p style="line-height: 29px; text-indent: 21px;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">8.保险代理人的激励机制研究.西安工程科技学院项目.</span></p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;">&nbsp;</p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">【论文】</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">1.</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">和征</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">王进富</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">李勃</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">杨小红</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">, </span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">制造企业业务外包的关系契约激励模型</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"> <span style="font-family: 宋体;">技术经济与管理研究</span>,2018</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">1:41-45</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">.</span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">2.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">, </span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">庄贵军</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">张正林等</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"> ,<span style="font-family: 宋体;">声誉、关系长度、渠道治理：农产品批发市场的实证研究</span><span style="font-family: Times New Roman;">, </span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">2017JMS<span style="font-family: 宋体;">中国营销科学学术年会及博士生论坛</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">论文集</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,<span style="font-family: 宋体;">广州</span><span style="font-family: Times New Roman;">,2017.11.10 .</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">3.<span style="font-family: 宋体;">和征</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">王进富</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">李勃</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">杨小红</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"> <span style="font-family: 宋体;">服务供应链信息共享的信任激励模型</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">, </span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">技术经济与管理研究</span>,201</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">7</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">1</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">1:</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">57</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">-</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">61.</span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">4.<span style="font-family: 宋体;">张正林</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">顾客参与、顾客满意与顾客信任的作用机制研究——基于两种自律导向的调节分析</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">预测</span><span style="font-family: Times New Roman;">,2016,01:43-48.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">5.Xiaohong Yang ,Qiuxia Xu, Characteristics of Direct Distributors<span style="font-family: 宋体;">’ </span><span style="font-family: Times New Roman;">Consumption Behavior and How Do They Influence on the Finance, The Thirteenth Wuhan International Conference on E-Business,wuhan,China,2014.5.31-6.1</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">6..Xiaohong Yang,Qiuxia Xu, A Review of Research Progress on Direct Selling in China Mainland and Taiwan, The Thirteenth Wuhan International Conference on E-Business,wuhan,China,2014.5.31-6.1</span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">7.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">续秋霞</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">直销商的领导行为及其与收入的相关性</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">兰州交通大学学报</span><span style="font-family: Times New Roman;">,2014,02:58-61.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">8.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">续秋霞</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">直销商的销售业绩与个体因素的相关性研究</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">兰州交通大学学报</span><span style="font-family: Times New Roman;">,2013,05:64-67.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">9.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">戒除网瘾的家庭策略研究</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">社科纵横</span><span style="font-family: Times New Roman;">,2011,11:44-45.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">10.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">如何改变网瘾者的认知、情感与行为</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">内江科技</span><span style="font-family: Times New Roman;">,2011,12:18-19.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">11.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">周镭</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">成功直销商的领导特质</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">企业活力</span><span style="font-family: Times New Roman;">,2009,01:36-37.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">12.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">周镭</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">沟通模型与提升直销员沟通效果的研究</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">江苏商论</span><span style="font-family: Times New Roman;">,2009,02:36-38.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">13.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">杨靖</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">乔·吉拉德的系统销售法</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">现代企业</span><span style="font-family: Times New Roman;">,2009,09:54-55.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">14.<span style="font-family: 宋体;">周镭</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">杨彬</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">探讨顾客资产的确认</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">财会研究</span><span style="font-family: Times New Roman;">,2009,17:31-32+72.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">15.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">有效沟通的构成要素与技巧</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">商场现代化</span><span style="font-family: Times New Roman;">,2008,35:224.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">16.<span style="font-family: 宋体;">雷霞</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">高校无形资产会计问题探析</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">财会研究</span><span style="font-family: Times New Roman;">,2007,05:32-33.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">17.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">雷霞</span><span style="font-family: Times New Roman;">,</span><span style="font-family: 宋体;">许益锋</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">消费者情感体验的心理分析</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">兰州交通大学学报</span><span style="font-family: Times New Roman;">, 2007,05:46-49.</span></span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">18.<span style="font-family: 宋体;">杨小红</span><span style="font-family: Times New Roman;">. </span><span style="font-family: 宋体;">正确定位</span><span style="font-family: Times New Roman;">:</span><span style="font-family: 宋体;">保险代理人的首要激励因素</span><span style="font-family: Times New Roman;">[J]. </span><span style="font-family: 宋体;">甘肃科技纵横</span><span style="font-family: Times New Roman;">,2005,05:105-62.</span></span></p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;">&nbsp;</p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">【著</span></span><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">作</span></span><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">】</span></span></p>
          <p style="margin: 0px 0px 3px; line-height: 29px; text-indent: 28px; -ms-layout-grid-mode: char;"><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">1.</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">市场营销学（杨小</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">红</span></span> <span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">主编）</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">,</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">中国纺织出版社</span></span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">2016</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">.1.撰写</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">10万字</span><span style="font-family: 宋体; font-size: 14px; font-weight: normal;">.</span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">2</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">．国际市场营销学（成爱武</span></span> <span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">主编）</span></span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">机械工业出版社</span></span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">2011</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">参编</span>10万字</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">3</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">．领导学（宋超英</span> <span style="font-family: 宋体;">主编）</span></span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">兰州大学出版社</span></span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">2003</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">参编</span>6万字</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span></p>
          <p style="line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric;"><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">4</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">．组织行为学（宋超英</span> <span style="font-family: 宋体;">主编）</span></span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">甘肃人民出版社</span></span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">2002</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">参编</span>10万字</span><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">.</span></p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;">&nbsp;</p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">【获奖】</span></span></p>
          <p style="background: rgb(255, 255, 255); text-align: left; line-height: 150%; text-indent: 28px; -ms-text-autospace: ideograph-numeric; -ms-word-break: break-all;"><span style="line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">优秀班主任。西安工程大学</span>2013-2014、2014-2015学年优秀教师。2016年获西安工程大学第十次优秀教材三等奖。成爱武主编，杨小红副主编，机械工业出版社出版的《国际市场营销学》，荣获2016年陕西省普通高校优秀教材奖二等奖。在各类征文比赛中多次获得一等奖、二等奖。</span></p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;">&nbsp;</p>
          <p style="line-height: 150%; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"><span style="font-family: 宋体;">【联系方式】</span> </span></p>
          <p style="padding: 0px; line-height: 150%; -ms-text-autospace: ideograph-numeric;"><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">Tel: &nbsp;</span><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;"> 13379231810 &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="background: rgb(255, 255, 255); color: rgb(102, 102, 102); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">Email:</span> <a href="mailto:1154318028@qq.com"><span style="background: rgb(255, 255, 255); color: rgb(51, 51, 51); line-height: 150%; font-family: 宋体; font-size: 14px; font-weight: normal;">1154318028@qq.com</span></a></p>
          <p></p><div id="div_vote_id"></div>
        </div>
        <div class="main_art">
          <ul>
            <li><lable>上一篇：</lable><a href="5089.htm">和征</a></li>
            <li><lable>下一篇：</lable><a href="4887.htm">刘晓喆</a></li>
          </ul>
        </div>
      </div>
    </el-main>
  </el-container>
</template>

<script>
export default {
  name: "yxh"
}
</script>

<style scoped>
.main_content {
  width: 978px;
  margin: 0 auto;
  height: auto;
  overflow: hidden;
  background: #fff;
  border: 1px solid #EEEEEE;
  border-top: none;
}
.main_contit {
  width: 950px;
  margin: 0 auto;
  height: auto;
  overflow: hidden;
  border-bottom: 1px dashed #eee;
}
.main_contit h2 {
  width: 950px;
  text-align: center;
  line-height: 28px;
  font-size: 24px;
  color: #000000;
  font-weight: normal;
  margin-top: 46px;
}
.main_contit p {
  width: 950px;
  text-align: center;
  font-size: 14px;
  color: #999999;
  margin: 34px 0 10px 0;
}
.main_conDiv {
  text-indent: 2em;
  font-size: 14px;
  line-height: 30px;
  color: #666666;
}
.main_art {
  width: 978px;
  margin: 72px auto 0;
  background: #fbfbfb;
  height: auto;
  overflow: hidden;
}
</style>